### ISSUE TITLE
Parameter count mismatch error when running InsertGetIdAsync<int>

### ISSUE THREAD

**Issue by hussamelvani** [sqlkata/querybuilder#331] opened 2020-01-06 07:56 UTC
I am using the following line of code to insert a record into DB, `employeesInformation` parameter is of type `Dictionary<string, object> ` and has 33 parameters.

`await sqlKataDB.Query("TBL_EMPLOYEES_INFORMATION").InsertGetIdAsync<int>(employeesInformation);`

I am getting Parameter count mismatch error. As far as I have seen online, this error occurs when you Invoke a delegate function with wrong parameters (I am not sure here). I tried making the fuction sync instead of async but that didn't help. 

I saw an open StackOverFlow ticket with the same error but with no answer, the OP was intructed to get RawSql and Bindigns, I can get you that if that helps (But I don't know how, instructions would be great!)

Any suggestions?

**Comment by ahmad-moussawi** [comment] 2020-01-06 07:58
could you please post a reproducible example?

**Comment by hussamelvani** [comment] 2020-01-06 09:03
[ParameterCountMismatch.zip](https://github.com/sqlkata/querybuilder/files/4025381/ParameterCountMismatch.zip)

I have attached the code that produces the error for me, I hope it is clear enough.

**Comment by ahmad-moussawi** [comment] 2020-01-07 20:59
@hussamelvani I still can't reproduce it, can't help without sharing a workable project so I can investigate it more,
mentioning the Database, Compiler and SqlKata version used.

**Comment by hussamelvani** [comment] 2020-01-08 07:20
@ahmad-moussawi I will try to reproduce it in a new project and get back to you because it is in a very big project that i unfortunately cannot share.
I will get back to you later with more information hopefully.
-Database: Microsoft SQL Server 2014.
-Compiler: SqlServerCompiler.
-SQLKata version: I tried 1.1.7 (latest stable at this time) through latest nightly 2.0.2 (latest at this time) with the same result.

**Comment by bmcmillan** [comment] 2020-01-12 03:36
The issue is that the Dictionary is being cast down to an object going from the async extension execution class to the Query.Insert.AsInsert  method and then the object is trying to be converted back into a dictionary, calling reflection methods on that dictionary thinking it's an object with properties that may have data annotations.

I think you just need to add an overload method explicitly for that dictionary type.

**Comment by hussamelvani** [comment] 2020-01-13 10:25
@bmcmillan I solved the issue by removing the Dictionary and typing the parameters one by one instead of passing them as a parameter, and that basically solved my problem.

**Comment by RichardAnderson** [comment] 2020-01-26 00:18
Hi,

Getting the same issue.
This did not happen prevously, but when upgrading a project to .net core 3.0 and the latest stable release of SQLKata, I get the same issue.

Code as below:

`public async Task Create(EntityBase record)
        {
            // Create a new Dictionary
            // with all the metadata
            var data = new Dictionary<string, object>(record.Values);

            // Remove fields we do NOT want the user to set:
            data.Remove(EntityBase.CoreAttributes.Id);

            // Run the query... 
            var response = await Query()
                .From(record.TableName)
                .InsertGetIdAsync<int>(
                    data
                );

            // Return the response...
            record.Id = response;

            // Finally.. Clear out the changes!
            record.Changes = null;
        }
`

As others have said above - this is due to a dictionary being passed in (cannot replicate if I pass in a dynamic object).

Any suggestions on how to overcome this issue?  Changing from a Dictionary is not an option for me in this project.

**Comment by RichardAnderson** [comment] 2020-01-26 01:07
Sumitted a Pull request - I have confirmed the changes made resolve the issue.

**Comment by ahmad-moussawi** [comment] 2020-01-26 11:27
Thanks guys, I merged @RichardAnderson's PR now.

**Closed** 2020-01-27 19:24 UTC
