### ISSUE TITLE
OUTPUT/RETURNING Clause Support for Inserts/Updates/Deletes

### ISSUE THREAD

**Issue by freakingawesome** [sqlkata/querybuilder#133] opened 2018-09-04 19:07 UTC
Is there any plan on supporting `OUTPUT` (SQL Server) or `RETURNING` (PostgresQL) clauses for mutations? This would, for example, allow me to fetch the GUIDs that were inserted:

Example in SQL Server Dialect that also includes the name as well just to show that it can be a full result set with multiple fields and rows:

```sql
CREATE TABLE #Foo ( ID UNIQUEIDENTIFIER, Name NVARCHAR(100) )

INSERT #Foo
OUTPUT INSERTED.ID, INSERTED.Name
VALUES (NEWID(), 'A'), (NEWID(), 'B'), (NEWID(), 'C')
```

Example output

| ID | Name |
| --- | --- |
| D5D898B0-DDB0-49DF-B57E-C43E95978274 | A |
| 43E82C23-BD3E-45E9-ADBD-F77264C9A795 | B |
| E08C3E50-AC3A-42D9-BFA5-C86E360790AE | C |

**Comment by ahmad-moussawi** [comment] 2018-09-11 07:32
Yes planned for the the v1.1, but the example you posted cannot be accomplished as is, since the Query Builder does not have any information about the table

**Comment by ElementalCyclone** [comment] 2019-02-20 15:43
> 
> 
> Yes planned for the the v1.1, but the example you posted cannot be accomplished as is, since the Query Builder does not have any information about the table

i think the given example is complete enough, since we can assume that the programmer stores the `CREATE`-ed table name and able to pass it to Query builder

and anyway
Has this feature added yet ? is there any update(s) ?

**Comment by basil-twisleton** [comment] 2020-01-20 12:50
It should be easy enough to do something like this passing in the requested column (or columns)

return db.Query(table).Output("ID").Output("Name".Insert();

Would be great to have this in my current project.

**Comment by NicolasMalo** [comment] 2020-02-11 15:13
This would be useful when deleting rows and wanting information about the deleted rows. Right now I have a workaround of selecting and then deleting in another query. It works, but it's slower since it makes 2 calls to the database.

Definitely would be a great feature to add.

**Comment by ahmad-moussawi** [comment] 2020-06-08 09:15
Closing this duplicate of #8

**Closed by ahmad-moussawi** 2020-06-08 09:15 UTC

**Comment by PhilConnor** [comment] 2022-03-09 16:47
Hi, why is this not a priority? 
I thought that avoiding extra roundtrips when doing operations on data was a good practice. Supporting "OUTPUT" or "RETURNING" statements would allow that.
I tried doing a "CombineRaw(" RETURNING *") but SqlKata does not surpport combines on update or inserts...
Any other workaround other than having to append this on the sql string?

**Comment by gsfarm** [comment] 2022-09-01 17:28
Yeah, working with `Guid` / `uuid` is difficult if the `uuid` is generated on the server side, for example, by `gen_random_uuid`, a variant with the suffix `SELECT lastval() AS id;` does not work. For now solution requires overriding `CompileInsertQuery` in own `PostgresCompiler` version.

**Comment by JakeAlmer** [comment] 2024-01-11 13:39
for anyone else watching as far as I can tell this done in this PR: https://github.com/sqlkata/querybuilder/pull/372/ 

unfortunately it shows no signs of getting merged
