### ISSUE TITLE
Use column name for parameters instead of @p0 , @p1

### ISSUE THREAD

**Issue by mnns** [sqlkata/querybuilder#423] opened 2020-11-01 14:21 UTC
That would be extremely helpful in several use cases.
For me, I'm trying to get a nice sql query builder, without using its query mechanism.
I'd just like to have the final query with parameters.
 
i.e. 
`SELECT * FROM c WHERE Name = @Name`

instead of `Name = @p0`

If there was a flag that would initiate this configuration in the compiler abstract class, that would be great.

Thanks a lot.

**Comment by ahmad-moussawi** [comment] 2020-11-02 08:06
I will close here since it's a duplicate of #168

**Closed by ahmad-moussawi** 2020-11-02 08:06 UTC
