### ISSUE TITLE
System.Missing Method Exception

### ISSUE THREAD

**Issue by austinwilcox1** [sqlkata/querybuilder#392] opened 2020-06-10 20:23 UTC
I am currently getting a Missing method exception, here's the Error message details "Method not found: 'System.String Humanizeer.InflectorExtensions.Singularize", and also the code that I'm using to execute.

```c#
 using(SqlConnection conn = new SqlConnection(EmployeePortalConnectionString))
            {
                var db = new QueryFactory(conn, new SqlServerCompiler());

                var fullName = db.Query("UserInfo")
                .WhereLike("UserID", membershipUserName)
                .Select("Name")
                .Get();

                return "";
            }
```

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String Humanizer.InflectorExtensions.Singularize(System.String, Boolean)'.
  Source=SqlKata.Execution
  StackTrace:
   at SqlKata.Execution.QueryFactory.handleIncludes[T](Query query, IEnumerable`1 result) in C:\Projects\querybuilder\SqlKata.Execution\QueryFactory.cs:line 716
   at SqlKata.Execution.QueryFactory.Get[T](Query query, IDbTransaction transaction, Nullable`1 timeout) in C:\Projects\querybuilder\SqlKata.Execution\QueryFactory.cs:line 85
   at SqlKata.Execution.QueryExtensions.Get[T](Query query, IDbTransaction transaction, Nullable`1 timeout) in C:\Projects\querybuilder\SqlKata.Execution\Query.Extensions.cs:line 12
   at SqlKata.Execution.QueryExtensions.Get(Query query, IDbTransaction transaction, Nullable`1 timeout) in C:\Projects\querybuilder\SqlKata.Execution\Query.Extensions.cs:line 22
   at IOS_Meter_API.Helpers.Employee.FetchFullName(String membershipUserName) in C:\Users\Programmer-Mac\source\Workspaces\IOS Meter API\IOS Meter API\Helpers\Employee.cs:line 27
   at IOS_Meter_API.Controllers.LoginController.Login(User user) in C:\Users\Programmer-Mac\source\Workspaces\IOS Meter API\IOS Meter API\Controllers\LoginController.cs:line 42
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by ahmad-moussawi** [comment] 2020-06-11 07:27
It seems a conflict in Humanizer nuget package, could you share the package versions before and after the update.

**Comment by tomek14** [comment] 2020-06-17 09:49
I've got same problem. I am using Humanizer.Core.pl version 2.8.26. As a workaround I downgraded to version 2.6.2.

**Comment by harishrathi** [comment] 2020-07-02 02:41
Downgrading `Humanizer` does solve the issue

**Comment by kunyanist** [comment] 2020-08-20 07:32
I've got same problem. I rolled back sqlKata.Execution to 1.1.7 and remove Humanizer.

**Comment by safayatzisan** [comment] 2021-01-26 07:26
@ahmad-moussawi please update Humanizer.Core to latest build. I got the same error. I manually modified your code and updated. 

I also added an overload for InsertAsync. Can I push this branch to you?

**Comment by ahmad-moussawi** [comment] 2021-03-14 18:48
duplicate of #435

**Closed by ahmad-moussawi** 2021-03-14 18:48 UTC
