### ISSUE TITLE
Query assignments with side effects

### ISSUE THREAD

**Issue by brgrz** [sqlkata/querybuilder#404] opened 2020-08-15 08:46 UTC
I only just discovered that calling most methods on the existing Query modifies/mutates the query instance instead of returning new instance. So even if no left-side assignment is made the query is modified.

For instance

```
var qb = query.Query;
var countQuery = qb.AsCount();
```

both qb and countQuery are the same after applying qb.AsCount(). 

I am trying to manipulate queries based on certain conditions and would like to keep the original query for later.

I found Clone() method, is that the only way to go?

**Comment by ahmad-moussawi** [comment] 2020-08-15 13:52
Yes this is by design, as you have mentioned `.Clone()` is what you want here.

**Comment by brgrz** [comment] 2020-08-17 11:30
What about immutable query, would you consider supporting that?

**Comment by ahmad-moussawi** [comment] 2020-08-17 15:16
There is no plan for this, unless there is a valid reason to do this, check this thread #176 
anyway, we are open to discussing more this.

**Comment by brgrz** [comment] 2020-08-17 17:58
As the other guy pointed out EF is doing it in immutable way also the methods even though they are not extension methods they look similar to extension methods and for those one typically assumes they return new instances.

I'm not sure whether memory consumption would go through the roof (I could be wrong though).

The way I found out about this is when I ran into issues when I wasn't doing the assignment and the original query mutated anyway.

I don't particularly mind the Clone() but it does introduce certain noise imo.

**Comment by asherber** [comment] 2021-06-23 00:43
I would also vote for an immutable pattern. I'm not sure why you say that memory consumption would go up, since on each assignment the old object would fall out of scope (and eventually be garbage collected).

**Comment by brgrz** [comment] 2022-01-05 21:07
This remains open and I'd hope plans would be revealed if this is planned for any version or maybe the next major version?

I'd imagine going from mutated queries to immutable ones is a breaking change, isn't it?

**Comment by ahmad-moussawi** [comment] 2022-10-02 09:02
Making the query immutable requires major rewriting, and honestly I don't see the clear benefit for it, the `query.Clone()` provide a handy way to do that, when needed.
So I will close this one, since there is no plan for it at the time being.

**Closed by ahmad-moussawi** 2022-10-02 09:02 UTC
Labels: need_investigation
