### ISSUE TITLE
Сompiling large queries takes a long time

### ISSUE THREAD

**Issue by alex-tselikovsky** [sqlkata/querybuilder#402] opened 2020-07-21 15:49 UTC
When generating a large query, performance drops significantly. Problem identified during research of Helper.cs (https://github.com/sqlkata/querybuilder/blob/master/QueryBuilder/Helper.cs)  in the ‘ReplaceAll’ method on line 92 where string concatenation occurs.
![image](https://user-images.githubusercontent.com/43967786/88075739-e3208380-cb81-11ea-81ee-2f715baaddd2.png)

Replacing it with the code below solves the problem.
` .Aggregate(new StringBuilder(splitted.First()), (prev, right) => prev.Append(right))`
 Pull Request for this reason can be found at the link.
https://github.com/sqlkata/querybuilder/pull/342/commits/c54f509b0e802b2c79b4f63a82b80e465910023e

**Comment by ahmad-moussawi** [comment] 2020-07-22 15:46
@alex-tselikovsky do you have any benchmarks

**Comment by for7raid** [comment] 2020-07-22 17:38
sound reasonable, but implementation have a questions.
`callback(index) + item`  reproduces the same issue - multiple coping strings in memory. so we have to replace both `select` and `aggregate` using in one  expression, like reduce in javascript.

**Comment by ahmad-moussawi** [comment] 2021-03-14 18:43
Closing this since no feedback.

**Closed by ahmad-moussawi** 2021-03-14 18:43 UTC

**Comment by viveks7** [comment] 2022-12-30 05:53
@ahmad-moussawi We are also seeing a similar pattern with generating larger queries where the bulk of the allocation is happening in the `ReplaceAll` method.
